schema:
  input:
    file: "src/PgCs.Cli/Examples/Sql/Schema/Schema.sql"
  output:
    directory: "src/PgCs.Cli/Examples/Generated/Models"
    namespace: "MyApp.Database.Models"

queries:
  input:
    file: "src/PgCs.Cli/Examples/Sql/Queries/Queries.sql"
  output:
    directory: "src/PgCs.Cli/Examples/Generated/Repositories"
    namespace: "MyApp.Database.Repositories"