schema:
  input:
    file: "/Users/valerijvorobev/Projects/pgcs/src/PgCs.Cli/Examples/Sql/Schema/schema_min.sql"
  output:
    directory: "/Users/valerijvorobev/Projects/pgcs/src/PgCs.Cli/Examples/Generated/Models"
    namespace: "MyApp.Database.Models"

queries:
  input:
    file: "/Users/valerijvorobev/Projects/pgcs/src/PgCs.Cli/Examples/Sql/Queries/queries_mini.sql"
  output:
    directory: "/Users/valerijvorobev/Projects/pgcs/src/PgCs.Cli/Examples/Generated/Repository"
    namespace: "MyApp.Database.Repository"