using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace PgCs.Common.CodeGeneration;

/// <summary>
/// Общие helper методы для работы с Roslyn syntax trees
/// </summary>
public static class RoslynSyntaxHelpers
{
    /// <summary>
    /// Создает header комментарий для auto-generated файлов
    /// </summary>
    public static SyntaxTriviaList CreateAutoGeneratedHeader()
    {
        return TriviaList(
            Comment("// <auto-generated>"),
            Comment(Environment.NewLine + "// This file was automatically generated by PgCs."),
            Comment(Environment.NewLine + "// DO NOT EDIT THIS FILE MANUALLY. Any changes will be lost on the next code generation."),
            Comment(Environment.NewLine + "// For more information, visit: https://github.com/yourusername/pgcs"),
            Comment(Environment.NewLine + "// </auto-generated>"),
            Comment(Environment.NewLine + Environment.NewLine)
        );
    }
}
